# ~form 开头的内容用于指定表单属性
~form:
  _subject: "Add product"
  _addanother: true
  _continue: true

# 指定字段及过滤器等信息
channelid:
  _ui: hidden

en_name:
  _ui: textbox
  _filters: ['trim']
  _label: "English name"
  _req: true

po_name:
  _ui: textbox
  _filters: ['trim']
  _label: "Portuguese name"
  _req: true

hidden:
  _ui: radiogroup
  _label: "Displays"
  _req: true

order:
  _ui: textbox
  _label: "Product sorting"
  _req: true
  
large_pic:
  _ui: upload
  _label: "Pictures"
  class: "vTextField"
  _tips: "recommended size: 620px * 280px"
  _req: true

en_intro1:
  _ui: memo
  _label: "English Text1"
  class: "vLargeTextField"
  rows: 5
  cols: 40
  _req: true

en_intro2:
  _ui: memo
  _label: "English Text2"
  class: "vLargeTextField"
  rows: 10
  cols: 40
  _req: true

po_intro1:
  _ui: memo
  _label: "Portuguese Text1"
  class: "vLargeTextField"
  rows: 5
  cols: 40


po_intro2:
  _ui: memo
  _label: "Portuguese Text2"
  class: "vLargeTextField"
  rows: 10
  cols: 40

supplier:
  _ui: textbox
  _label: "Supplier"
  class: "vTextField"

supplier_code:
  _ui: textbox
  _label: "Supplier Code"
  class: "vTextField"

cost:
  _ui: textbox
  _label: "Cost"
  class: "vTextField"

sales_price:
  _ui: textbox
  _label: "Sales Price"
  class: "vTextField"

moq:
  _ui: textbox
  _label: "MOQ"
  class: "vTextField"

size:
  _ui: textbox
  _label: "Size"
  class: "vTextField"

weight:
  _ui: textbox
  _label: "Weight"
  class: "vTextField"

volime:
  _ui: textbox
  _label: "Volime"
  class: "vTextField"

packing_size:
  _ui: textbox
  _label: "Packing Size"
  class: "vTextField"

packing_qty:
  _ui: textbox
  _label: "Packing QTY"
  class: "vTextField"

loading_20:
  _ui: textbox
  _label: "Loading 20'"
  class: "vTextField"
  
loading_40:
  _ui: textbox
  _label: "Loading 40'"
  class: "vTextField"
  
loading_40hc:
  _ui: textbox
  _label: "Loading 40'HC"
  class: "vTextField"

brand:
  _ui: textbox
  _label: "Brand"
  class: "vTextField"